import { auth } from "../firebase"
import useFetchUserDetails from "../hooks/useFetchUserDetails"

export const images = (username) => [
    `https://api.dicebear.com/9.x/initials/svg?seed=${username}?size=96`,
    `${process.env.PUBLIC_URL}/1.jpeg`,
    `${process.env.PUBLIC_URL}/2.jpeg`,
    `${process.env.PUBLIC_URL}/3.jpeg`,
    `${process.env.PUBLIC_URL}/4.jpeg`,
    `${process.env.PUBLIC_URL}/5.jpeg`,
    `${process.env.PUBLIC_URL}/6.jpeg`,
    `${process.env.PUBLIC_URL}/7.jpeg`,
    `${process.env.PUBLIC_URL}/8.jpeg`,
    `${process.env.PUBLIC_URL}/9.jpeg`,
    `${process.env.PUBLIC_URL}/10.jpeg`,
    `${process.env.PUBLIC_URL}/11.jpeg`,
    `${process.env.PUBLIC_URL}/12.jpeg`,
    `${process.env.PUBLIC_URL}/13.jpeg`,
    `${process.env.PUBLIC_URL}/14.jpeg`,
    `${process.env.PUBLIC_URL}/15.jpeg`,
    `${process.env.PUBLIC_URL}/16.jpeg`,
    `${process.env.PUBLIC_URL}/17.jpeg`,
    `${process.env.PUBLIC_URL}/18.jpeg`,
    `${process.env.PUBLIC_URL}/19.jpeg`,
    `${process.env.PUBLIC_URL}/20.jpeg`,
    `${process.env.PUBLIC_URL}/21.jpeg`,
    `${process.env.PUBLIC_URL}/22.jpeg`,
    `https://api.dicebear.com/9.x/dylan/svg?seed=${username}?size=96`,
    `https://api.dicebear.com/9.x/adventurer-neutral/svg?seed=${username}?size=96`,
    `https://api.dicebear.com/9.x/fun-emoji/svg?seed=${username}?size=96`,
    `https://api.dicebear.com/9.x/thumbs/svg?seed=${username}?size=96`,
    `https://api.dicebear.com/9.x/notionists/svg?seed=${username}?size=96`,
    `https://api.dicebear.com/9.x/micah/svg?seed=${username}?size=96`,
    `https://api.dicebear.com/9.x/open-peeps/svg?seed=${username}?size=96`,
    `https://api.dicebear.com/9.x/adventurer/svg?seed=${username}?size=96`,
]